bug:
  - '(?i)(bug|fout|error|exception|traceback|crash|not working|werkt niet|kapot|broken|failing|does not work|stopped working)'

enhancement:
  - '(?i)(feature|enhancement|feature request|verbeter|toevoeg|add support|support for|request|wish|suggestie|suggestion|could you|can you add)'

question:
  - '(?i)(question|vraag|how to|hoe|what is|help|uitleg|explain|why|confused|understand)'

documentation:
  - '(?i)(docs|documentation|readme|example|guide|how to configure)'

docker:
  - '(?i)(docker|container|image|pull|compose|ghcr|registry|dockerfile)'

"home assistant":
  - '(?i)(home assistant|hass|addon|add-on|homeassistant)'

configuration:
  - '(?i)(config|configuratie|setup|install|options|settings|configure|parameter)'

performance:
  - '(?i)(slow|traag|performance|memory|cpu|hang|freeze|timeout|lagging)'

dependencies:
  - '(?i)(dependency|requirement|package|pip|version incompatible)'
